version: '2'
services:
  pesto:
    build: ./pesto
    depends_on: 
      - basil
    ports:
      - "80:80"
  basil:
    build: ./basil
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: pV7JuwTj7FAjDG3B
      MYSQL_DATABASE: basil
      MYSQL_USER: basil
      MYSQL_PASSWORD: pV7JuwTj7FAjDG3B
