basil:
  build: .
  ports: 
    - "8080:8080"
  volumes:
    - .:/basil
  links:
    - db:db
db:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: pV7JuwTj7FAjDG3B
    MYSQL_DATABASE: basil
    MYSQL_USER: basil
    MYSQL_PASSWORD: pV7JuwTj7FAjDG3B
