version: '2'
services:
  pesto:
    build:
      context: ./pesto
      args:
        BASIL_HOST: localhost
    links: 
      - basil
    ports:
      - "80:80"
  basil:
    build: ./basil
    links:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: pV7JuwTj7FAjDG3B
      MYSQL_DATABASE: basil
      MYSQL_USER: basil
      MYSQL_PASSWORD: pV7JuwTj7FAjDG3B
